if ("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
	include(cmake/linux.cmake)
elseif ("${CMAKE_SYSTEM_NAME}" STREQUAL "Darwin")
	include(cmake/mac.cmake)
elseif ("${CMAKE_SYSTEM_NAME}" STREQUAL "Windows")
	include(cmake/windows.cmake)
else()
	message(FATAL_ERROR "Unsupported platform: ${CMAKE_SYSTEM_NAME}")
endif()
