set(ENV{DCORE_COMPILE_DEFINITIONS} "-DDCORE_PLAT_WINDOWS")
set(DCORE_PLAT_WINDOWS 1)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /std:c++17 /permissive- -DBOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -DNOMAXMIN -D_CRT_SECURE_NO_WARNINGS")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ")
